# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Willkommen"
  url = "docs/"
  weight = 1

 [[main]]
  name = "Handwerkszeug"
  url = "docs/1_handwerkszeug/"
  weight = 2

[[main]]
  name = "Quellenarbeit"
  url = "docs/2_quellenarbeit/"
  weight = 3

#[[main]]
#  name = "Schreiben"
#  url = "docs/3_schreiben/"
#  weight = 4

[[main]]
  name = "TH Research Guide"
  url = "docs/8_TH_research_guide/"
  weight = 8

[[main]]
  name = "Impressum"
  url = "docs/9_impressum/"
  weight = 9